on:
  workflow_dispatch:
    inputs:
      tagName:
        required: true
        description: 'Tag name of this release'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set tag name from workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tagName }}" >> $GITHUB_ENV
      -
        name: Failure tag name not found
        if: env.TAG_NAME == ''
        run: exit 1
      -
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      -
        uses: docker/setup-buildx-action@v1
      -
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-mastodon:${{ env.TAG_NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
